### ISSUE TITLE
Not working with Magento 2.4.6-p1 (method_exists() error)

### ISSUE THREAD

**Issue by avstaylime** [experius/Magento-2-Module-Experius-Email-Catcher#68]
When trying to send an email via Send Email from the order page, I get the error below.

```php
TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /data/web/magento2/vendor/experius/module-emailcatcher/Model/Emailcatcher.php:81
Stack trace:
#0 /data/web/magento2/vendor/experius/module-emailcatcher/Model/Emailcatcher.php(81): method_exists()
#1 /data/web/magento2/vendor/experius/module-emailcatcher/Plugin/Magento/Framework/Mail/TransportInterface.php(94): Experius\EmailCatcher\Model\Emailcatcher->saveMessage()
#2 /data/web/magento2/vendor/experius/module-emailcatcher/Plugin/Magento/Framework/Mail/TransportInterface.php(67): Experius\EmailCatcher\Plugin\Magento\Framework\Mail\TransportInterface->saveMessage()
#3 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Experius\EmailCatcher\Plugin\Magento\Framework\Mail\TransportInterface->aroundSendMessage()
#4 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Amasty\Smtp\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#5 /data/web/magento2/generated/code/Amasty/Smtp/Model/Transport/Interceptor.php(23): Amasty\Smtp\Model\Transport\Interceptor->___callPlugins()
#6 /data/web/magento2/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(75): Amasty\Smtp\Model\Transport\Interceptor->sendMessage()
#7 /data/web/magento2/vendor/magento/module-sales/Model/Order/Email/Sender.php(86): Magento\Sales\Model\Order\Email\SenderBuilder->send()
#8 /data/web/magento2/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php(108): Magento\Sales\Model\Order\Email\Sender->checkAndSend()
#9 /data/web/magento2/vendor/bigfishpaymentgateway/pmgw/Model/Order/Email/Sender/OrderSender.php(37): Magento\Sales\Model\Order\Email\Sender\OrderSender->send()
#10 /data/web/magento2/vendor/magento/module-sales/Model/AbstractNotifier.php(59): Bigfishpaymentgateway\Pmgw\Model\Order\Email\Sender\OrderSender->send()
#11 /data/web/magento2/vendor/magento/module-sales/Model/Service/OrderService.php(157): Magento\Sales\Model\AbstractNotifier->notify()
#12 /data/web/magento2/vendor/magento/module-sales/Controller/Adminhtml/Order/Email.php(27): Magento\Sales\Model\Service\OrderService->notify()
#13 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Email->execute()
#14 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->___callParent()
#15 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->Magento\Framework\Interception\{closure}()
#16 /data/web/magento2/generated/code/Magento/Sales/Controller/Adminhtml/Order/Email/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->___callPlugins()
#17 /data/web/magento2/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->execute()
#18 /data/web/magento2/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#19 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#20 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->___callParent()
#21 /data/web/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->Magento\Framework\Interception\{closure}()
#22 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#23 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->Magento\Framework\Interception\{closure}()
#24 /data/web/magento2/generated/code/Magento/Sales/Controller/Adminhtml/Order/Email/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->___callPlugins()
#25 /data/web/magento2/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Email\Interceptor->dispatch()
#26 /data/web/magento2/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#27 /data/web/magento2/vendor/magento/framework/App/FrontController.php(146): Magento\Framework\App\FrontController->processRequest()
#28 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#29 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#30 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#31 /data/web/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#32 /data/web/magento2/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#33 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#34 /data/web/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#35 {main}
```

**Comment by borisvankatwijk** [comment]
Hi @avstaylime,

It looks like your $bodyObject, or $message, is of the value **null**.

Perhaps this is an issue with the email (template).
Or has this perhaps been resolved in another way?

Kind regards, Boris

**Comment by MatthijsBreed** [comment]
@avstaylime 
This is an incompatibility with the Amasty_Smtp module, since that module overrides the core Magento transport and email classes.
Since Magento provides SMTP functionality in 2.4.6+ and the emailcatcher takes care of logging, you could consider uninstalling that module

**Comment by avstaylime** [comment]
> @avstaylime
> This is an incompatibility with the Amasty_Smtp module, since that module overrides the core Magento transport and email classes.
> Since Magento provides SMTP functionality in 2.4.6+ and the emailcatcher takes care of logging, you could consider uninstalling that module

Thanks @MatthijsBreed, that is correct. I should have closed this issue when I realized that a few weeks back.
